# Base configs
baseurl: ""
url: "http://oscarlimajr.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Danielita's Birthday Disney Family Trip by Oscar Lima"
subtitle: "See the world through my eyes!"
author: "Oscar Lima"
bio: "Daniela Lima Birthday Trip"
web_design: "AJ"
  
